"""(officially) created class_check table

Revision ID: 19a18ef252e5
Revises: 
Create Date: 2019-05-30 15:33:13.070630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a18ef252e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('time_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_check')
    # ### end Alembic commands ###
